FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    faker==22.2.0 \
    pandas==2.1.4 \
    numpy==1.26.3 \
    python-dotenv==1.0.0

# context is project root
COPY kafka/producer/ecommerce_producer.py ./kafka/producer/
COPY data/sample/ ./data/sample/

ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV PYTHONUNBUFFERED=1

CMD ["python", "kafka/producer/ecommerce_producer.py", "--rate", "5"]